# Generated by Django 5.1.3 on 2024-11-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
